<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="SQL_CAD_CONVENIO.php" method="post">

Convênio:
<input type="text" name="frm_conv"> <br>
Cooparticipação:
<input type="number" name="frm_coo">

<button type="submit">Enviar</button>


</form>
</body>
</html>

